[package]
name = "miror"
version = "0.0.0"
edition = "2024"
authors = ["Andy Hsu", "3261429104atqq.com"]
license.workspace = true
readme = "readme.md"
categories = ["p2p", "quiclike", "network-programming", "tobacco"]
description = "P2P support for quiclike protocol."

[dependencies]
