[package]
name = "colloid"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Crypto layer abstraction for smog."

[dependencies]
