[package]
name = "quiclike"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "API re-exports for quiclike project."

[dependencies]
